# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in api001.gemspec
gemspec

gem "rake", "~> 13.0"
gem 'sinatra'
gem 'sinatra-contrib'
gem "rackup", "~> 2.1"
gem 'mongo'
gem 'json'
